import { API_ENDPOINT_QUERY, BASE_URL_BE_DEVELOPMENT, BASE_URL } from "../../constants/url";

export const API = {
  API_GET_ALL_USERS: BASE_URL,
  API_GET_USER_DETAIL: BASE_URL+API_ENDPOINT_QUERY.USER_DETAIL,
  API_RECHARGE_WALLET: BASE_URL+API_ENDPOINT_QUERY.RECHARGE_WALLET
};
