import { API_ENDPOINT_QUERY, BASE_URL } from "../../constants/url";

export const API = {
  API_GET_ALL_USERS: BASE_URL,
  API_GET_USER_DETAIL: BASE_URL+API_ENDPOINT_QUERY.USER_DETAIL,
  API_RECHARGE_WALLET: BASE_URL+API_ENDPOINT_QUERY.RECHARGE_WALLET,
  API_WITHDRAW_WALLET: BASE_URL+API_ENDPOINT_QUERY.WITHDRAW_WALLET,
  API_GET_COURSE_BY_USER: BASE_URL+API_ENDPOINT_QUERY.GET_COURSE_BY_USER
};
