import { API_ENDPOINT_QUERY, BASE_URL_BE_DEVELOPMENT } from "../../constants/url";

export const API = {
  API_GET_ALL_USERS: BASE_URL_BE_DEVELOPMENT,
  API_GET_USER_DETAIL: BASE_URL_BE_DEVELOPMENT+API_ENDPOINT_QUERY.USER_DETAIL,
  API_RECHARGE_WALLET: BASE_URL_BE_DEVELOPMENT+API_ENDPOINT_QUERY.RECHARGE_WALLET
};
