import { API_ENDPOINT_QUERY, BASE_URL, } from "../../constants/url";

export const API = {
  API_GET_REPORT_LIST: BASE_URL+API_ENDPOINT_QUERY.GET_ALL_REPORT_LIST,
  API_POST_REPORT_LIST_BY_DATE: BASE_URL+API_ENDPOINT_QUERY.GET_REVENUE_BY_DATE
};
