import { API_ENDPOINT_QUERY, BASE_URL, } from "../../constants/url";

export const API = {
  API_GET_ALL_ORDERS: BASE_URL+API_ENDPOINT_QUERY.GET_ALL_ORDERS,
  API_GET_ORDER_DETAIL: BASE_URL+API_ENDPOINT_QUERY.GET_ORDER_DETAIL,

  
};
